- Cargo.lock
- Cargo.toml
- bins/fc_wrapper/main.rs
- bins/firerunner/main.rs
- microbenchmark/run.sh
- microbenchmark/run_scripts/run_fullapp.sh
- microbenchmark/run_scripts/run_regular.sh
- microbenchmark/setup_scripts/build_binaries.sh
- src/controller.rs
- src/vm.rs
By default, `rootfs`, `appfs`, `diff snapshot` are opened with O_DIRECT set.
When using `fc_wrapper`, pass `--no_odirect_rootfs`, `--no_odirect_appfs`, `--no_odirect_diff` to open these files without O_DIRECT and pass `--odirect_base` to open base snapshot memory file with O_DIRECT.
`snapctr` always uses the default setting.
> Optionally set O_DIRECT for block device files and snapshot memory files

- Cargo.lock
- Cargo.toml
- bins/fc_wrapper/main.rs
- shell.nix
- src/controller.rs
- src/vm.rs
- src/worker.rs
When starting a VM we currently wait for a vsock connection from the VM. However, the VM may die before that happens, in which we want to return early rather than block indefinitely.
This PR accomplishes that using using tokio's select! to block on _either_ vsock connection _or_ the Child exiting during VM creation.
> Wait for either child exit or vsock connection in VM creation

- Cargo.nix
- Cargo.toml
- bins/multivm/main.rs
- bins/sfclient/main.rs
- src/configs.rs
- src/gateway.rs
- src/request.rs
- src/worker.rs
This PR fixes one issue and adds a small utility for interacting with the multivm.
* Instead of busy-looping in the `gateway` module, which consumes 100% of a CPU-core when everything is otherwise idle, convert the gateway to a threaded server.
* Add a utility, `sfclient`, to send requests to `multivm` from the command-line. Useful at least for testing.
* Print out YAML parse error from `multivm` if reading the config file fails
The last couple commits include some nit cleanups that i accidentally committed such that they can't be easily separated, but they are not major features.
> General improvements to `multivm`

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/vm.rs
- src/worker.rs
LMDB environment should not be created more than once per process,
instead should be shared across threads.
See http://www.lmdb.tech/doc/starting.html#thrproc
This PR uses `lazy_static` to initialize the LMDB environment globally in `vm.rs` as a static variable.
> Create LMDB environment once globally

- bins/sfclient/main.rs
- frontends/webhook/Cargo.lock
- frontends/webhook/src/app.rs
- frontends/webhook/src/main.rs
- frontends/webhook/src/server.rs
- src/gateway.rs
- src/request.rs
- src/vm.rs
- src/worker.rs
This PR includes more cleanup in a few parts of the code.
* Removes the unused `user_id` field from the `Request` type for now
* Suppresses warnings for a necessary unused field in snapfaas (which now compiles without warnings)
* Moves the webhook frontend's snapfaas connection to the App module, shared via a Mutex. This should probably be replaced by a connection pool (e.g. r2d2), but we definitely don't want to create a new snapfaas connection per client-connection, and almost certainly want the connection logic in the app module, not the server module.
> Some general cleanup

- snapfaas/bins/multivm/main.rs
- snapfaas/src/gateway.rs
- snapfaas/src/message.rs
- snapfaas/src/metrics.rs
- snapfaas/src/request.rs
- snapfaas/src/vm.rs
- snapfaas/src/worker.rs
In addition to the existing four timestamps, for each request, log down a copy of the request and timestamps when it arrives at the gateway or at the VMM invoke handler.
> log request copies & timestamps at gateway/vmm

- Cargo.lock
- Cargo.nix
- snapfaas/Cargo.toml
- snapfaas/src/blobstore/mod.rs
- snapfaas/src/lib.rs
- snapfaas/src/syscalls.proto
- snapfaas/src/vm.rs
This pull request adds an immutable blob-store service to the snapfaas VMM. It is exposed to functions through a series of system calls that allow the function to create an empty, but un-namable blob, write data to it, and "finalize" it, resulting in the blob getting a content-addressable name (a SHA256 hash of the written content). Once a blob is "finalized" it can be opened and read (at any offset and length) by other functions, but can never be modified.
The file system abstraction (previous the key-value store) requires all reads and writes to be complete---i.e., you must read/write the contents of an entire key in one system call. For large values, this is problematic because it requires the entire value to be resident in memory, even if the application is consuming content in a …
> Add an immutable blobstore

- Cargo.lock
- snapfaas/Cargo.toml
- snapfaas/bins/README.md
- snapfaas/bins/sffs/main.rs
- snapfaas/src/labeled_fs/dir.rs
- snapfaas/src/labeled_fs/direntry.rs
- snapfaas/src/labeled_fs/mod.rs
Two main changes:
1. `sffs` binary, a command-line tool to read files and directories, create files and directories, and write files in the labeled file system. Respectively, the subcommands are `cat`, `ls`, `mkdir`, `mkfile`, `write`.
2. Addtionally, one main change to the existing `labeled_fs` module.
The module now uses random generated `uid`s instead of continuously incremented `uid`s.
Random generated `uid`s remove the need of persisting `next_uid`.
> Add `sffs` binary

- Cargo.lock
- Cargo.nix
- crate-hashes.json
- snapfaas/Cargo.toml
Updates crossbeam-channel to a newer version that doesn't rely on a buggy version of crossbeam-utils (crossbeam-rs/crossbeam#781)
> crossbeam-channel -> 0.5.5

- snapfaas/bins/firerunner/main.rs
- snapfaas/bins/singlevm/main.rs
- snapfaas/src/worker.rs
In case there are left-over socket files from a previous run, always
attempt to remove a socket file before creating it.
> Remove socket files before creation

- .gitignore
- Cargo.nix
- snapfaas/Cargo.toml
- snapfaas/bins/sfblob/main.rs
Adds a command line interface, `sfblob` for reading/writing blobs. For
writing, it takes input from stdin, stores it in the blobstore and
outputs the blob name to stdout. For reading, it takes one or more lines
of blob names on stdin and outputs the named blobs' contents to stdout.
> Add CLI writing/reading blobs

- frontends/webhook/src/app.rs
- snapfaas/src/metrics.rs
- snapfaas/src/request.rs
- snapfaas/src/worker.rs
This PR adds invocation retries in the worker. Each invocation is retried up to 5 times if there is any error in the invocation, before returning either a successful result or an error.
> Implement invocation retries for VM and other failures

- rootfs/mk_rtimage.sh
- rootfs/runtimes/nodejs/Makefile
- rootfs/runtimes/python3/Makefile
Updated the runtime Makefiles to compile the runtime-specific protobuf file from the local `syscalls.proto` given now all sources located in the same repository. `mk_rtimage` are updated accordingly.
> Build runtime-specific protobuf files from local syscalls.proto

- frontends/webfront/src/app.rs
- snapfaas/src/labeled_fs/mod.rs
- Increase the max_readers for lmdb dramatically from the default of 126 to 1024. This is important because we can easily have more than 126 worker threads + other processes taking a reader lock concurrently.
- Allow `invoke` access to a couple `cos326_` functions in-lieu of more general access control mechanisms for function invocation
> Small production fixes

- snapfaas/src/fs/mod.rs
- snapfaas/src/vm.rs
String formatted paths should not include an element for the (implicit) root directory
> Fix use of read_path to exclude leading string

- snapfaas/src/fs/mod.rs
- snapfaas/src/syscalls.proto
- snapfaas/src/vm.rs
1. Define the structure of a faceted directory object
`FacetedDirectoryInner`
3. The faceted counterparts
`faceted_list`, `faceted_link`, `faceted_unlink`, `create_faceted_directory`
5.  Three new protobuf syscalls
`FSList`, `FSFacetedList`, `FSCreateFacetedDir`
7. a helper function that used by read_path to traverse the file system tree
`open_facet`
> Implementation of the faceted directory and the faceted system calls

- snapfaas/bins/multivm/main.rs
- snapfaas/src/fs/mod.rs
- snapfaas/src/vm.rs
When the last component of the path is an unallocated facet for FsList, return empty vector
When the last component of the path is an unallocated facet for FsCreateXXX, if linking is allowed, allocate the facet.
> fix corner case where the last component is unallocated facet

- resources/hello.json
- rootfs/runtimes/python3/syscalls.py
- snapfaas/bins/sfclient/main.rs
- snapfaas/src/fs/mod.rs
- snapfaas/src/gateway.rs
- snapfaas/src/message.rs
- snapfaas/src/request.rs
- snapfaas/src/syscalls.proto
- snapfaas/src/vm.rs
- snapfaas/src/worker.rs
The scheduler now processes snapfass::request::LabeledInvoke.
The scheduler does no invoke check. An entry invocation gets checked inside sfclient. Invokes from a VM gets checked before submitted to the scheduler.
Sfclient now supports command-line invokes and new gate creation.
> Sketch of functional gate invocation.

- snapfaas/src/message.rs
- snapfaas/src/resource_manager.rs
- snapfaas/src/vm.rs
- snapfaas/src/worker.rs
The PR contains the change that checks a cached VM's label is less tainted than the invocation request.
Two things to note:
1. The path traversal to fetch the gate object and the check both happen at the invokee side.
2. Due to 1, the effective label of the request is the invoker VM's label at the time of invocation joined by all labels of the gate's parent directories.
> Checking cached VMs' labels

- functions/fsutil/workload.py
- rootfs/runtimes/python3/syscalls.py
- snapfaas/src/fs/bootstrap.rs
- snapfaas/src/fs/mod.rs
- snapfaas/src/fs/path.rs
- snapfaas/src/syscall_server.rs
- snapfaas/src/syscalls.proto
How is a redirect gate different from a normal gate?
* A normal gate object stores pointers to blob images required to boot a virtual machine for a function (kernel, runtime/root file system, app file system) and the virtual machine memory size.
* A regular gate object stores a Faasten-FS path, a redirection. The path should be a directory that has four entries---a blob entry named "kernel", a blob entry named "runtime", a blob entry named "app", and a file entry named "memory". These entries correspond to the three blob pointers and the specification on the virtual machine memory size in a normal gate object.
Changes to Faasten-FS interface  (`snapfaas/src/fs/mod.rs`):
* add a bool field `redirect` to the DirEntry type, Gate.
* add another Faasten-FS primitive `invoke_redirect` that …
> Add Redirect Gate

- snapfaas/src/fs/mod.rs
Changes:
1. All label checks are in `mod checks` now.
2. Fix faceted link/unlink to do the same label checks as link/unlink.
More on 2:
Before, faceted link/unlink did the read-check because it called `FacetedDirectoryInner`'s member function `open_facet` which did the read-check. 
Now, this `open_facet` renamed as `get_facet` no more does the read-check to reflect that it is only a helper function to get the directory at the facet. Instead, the `FS<S>`'s `open_facet` now does the read check.
> Fix faceted link/unlink label checks & move label checks into `mod checks`

- bootstrap-config.yml
- rootfs/runtimes/python3/syscalls.py
- snapfaas/bins/admin_fstools/main.rs
- snapfaas/src/fs/mod.rs
- snapfaas/src/fs/path.rs
- snapfaas/src/syscall_server.rs
- snapfaas/src/syscalls.proto
This PR contains a number of small nits found in the process of getting benchmarks working
1. Add `mkdir` and `blob` commands to `admin_fstools` to allow creating a directory and uploading a blob, respectively, to the datastore during bootstrap (e.g. to setup input files and output directories for benchmarking).
2. Fix a bug in linking facets that created the wrong facet
3. Add `seek` and `tell` operations to the python's `Blob` class so it can behave like a file in more cases
4. Get rid of the absolute path in the example bootstrap config.
5. Add an `FSOpenBlob` system call for retrieving a blob name by its file name
> Bits and bobs towards in pursuit of benchmarks working

- frontends/webfront/src/app.rs
- frontends/webfront/src/main.rs
- snapfaas/src/syscall_server.rs
- snapfaas/src/syscalls.proto
We're not using these APIs anymore, and don't intend to revive them in this form. They currently make deploying significantly more cumbersome than necessary, so let's get rid of them.
> Remove unused GitHub built-in functionality

- frontends/webfront/src/init.rs
- snapfaas/src/sched/messages.proto
- snapfaas/src/sched/rpc_server.rs
- snapfaas/src/syscall_server.rs
- snapfaas/src/worker.rs
The scheduler always returns the current label at the point of return and the gateway also uses the thread's current label (which is set in `init`) as the guard.
> Add label to TaskReturn and check label in gateway

- Cargo.lock
- default.nix
- frontends/webfront/Cargo.toml
- frontends/webfront/src/main.rs
- snapfaas/Cargo.toml
- snapfaas/bins/admin_fstools/main.rs
- snapfaas/bins/firerunner/main.rs
- snapfaas/bins/garbage-collector/main.rs
- snapfaas/bins/multivm/main.rs
- snapfaas/bins/scheduler/main.rs
- snapfaas/bins/singlevm/main.rs
- snapfaas/src/cli.rs
- snapfaas/src/configs.rs
- snapfaas/src/fs/lmdb.rs
- snapfaas/src/lib.rs
- snapfaas/src/vm.rs
The PR contains a reimplementation of the CLI commands using the new "derive" syntax.
The new syntax allows us to centralize a set of common arguments (snapfaas/src/cli.rs) and easily declares argument relationships. For example, one should specify exactly one of the tikv store and lmdb store (as this is required, the static DBENV is no longer needed and removed).
> Bump clap to 4.2.7

- Cargo.lock
- Cargo.toml
- default.nix
- frontends/webfront/Cargo.toml
- frontends/webfront/src/main.rs
- shell.nix
- snapfaas/Cargo.toml
- snapfaas/bins/admin_fstools/main.rs
- snapfaas/bins/multivm/main.rs
- snapfaas/bins/singlevm/main.rs
We have been using a git version of the TikV client along with git versions of specific dependencies in order to be able to compile. This turns out to be unnecessary as stock tikv-client simply requires building `gprcio-sys` with gcc10.
> Update to build with stock tikv

- snapfaas/bins/firerunner/main.rs
- snapfaas/bins/singlevm/main.rs
- snapfaas/src/cli.rs
- snapfaas/src/vm.rs
This patch fixes three problems:
1. CLI arguments should contain dashes instead of underscores
2. CLI argument groups `Load`, `Dump`, `Network` were wrongly specified
3. CLI odirect flags handling was wrong
> Fix CLI arguments

- Cargo.lock
- frontends/webfront/src/init.rs
- functions/build.sh
- functions/fsutil/workload.py
- functions/hello/workload.py
- functions/princeton-cas/login-bytes/workload.py
- functions/princeton-cas/login/workload.py
- rootfs/runtimes/python3/syscalls.py
- rootfs/runtimes/python3/workload.py
- snapfaas/Cargo.toml
- snapfaas/src/sched/message.rs
- snapfaas/src/sched/messages.proto
- snapfaas/src/syscall_server.rs
- snapfaas/src/syscalls.proto
This patch includes three commits:
1. adding two functions princeton-cas/login&login-bytes for testing and bootstrapping moving authentication into functions
2. the second's main change is in snapfaas/src/sched/message.rs, converting TaskReturn to HTTP response
3. add library support for new syscalls:Response and update fsutil and hello
> Make webfront act as a passthrough

- frontends/webfront/src/init.rs
- functions/Dockerfile-python
- functions/README.md
- functions/build.sh
- functions/docker_clean.sh
- functions/docker_install.sh
- functions/jwt/requirements.txt
- functions/jwt/workload.py
- rootfs/runtimes/python3/workload.py
- snapfaas/bins/admin_fstools/main.rs
- snapfaas/bins/singlevm/main.rs
- snapfaas/src/fs/utils.rs
- snapfaas/src/sched/messages.proto
- snapfaas/src/sched/mod.rs
- snapfaas/src/sched/rpc.rs
- snapfaas/src/sched/rpc_server.rs
- snapfaas/src/syscall_server.rs
- snapfaas/src/syscalls.proto
- snapfaas/src/worker.rs
A JWT function that reads the private key PEM and generates a JWT.
This patch also updated admin_fstools to generate public/private key pairs in the PEM format to Faasten file. This is part of system administration and can also help testing process. The JWT function is only tested using singlevm.
> Add JWT function
